name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        java-version: [17]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Compile Java code
        run: |
          mkdir -p out
          javac -cp "$JAVA_HOME/lib/*:libs/*:src/main/java" -d out $(find src/main/java -name "*.java")

      - name: Run unit tests
        run: |
          # Указываем путь к JUnit JAR файлам, добавленным в libs/
          java -cp "libs/*:out:libs/junit-platform-console-standalone-1.9.2.jar" org.junit.platform.console.ConsoleLauncher --select-class com.example.AppTest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run tests
        run: |
          # Указываем путь к JUnit JAR файлам, добавленным в libs/
          java -cp "libs/*:out:libs/junit-platform-console-standalone-1.9.2.jar" org.junit.platform.console.ConsoleLauncher --select-class com.example.AppTest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Remote Server
        run: |
          ssh user@Someone "cd /path/to/app && git pull && ./deploy.sh"
