name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java-version: [11, 17]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.5'

      - name: Ensure Gradle Wrapper
        run: |
          if [ ! -f ./gradlew ]; then
            echo "Gradle Wrapper not found, generating..."
            gradle wrapper
          fi

      - name: Build with Gradle
        run: ./gradlew build
