name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        java-version: [17]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Give execute permission to gradlew (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          if [[ $RUNNER_OS == 'Windows' ]]; then
            gradlew.bat build
          else
            ./gradlew build
          fi

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Give execute permission to gradlew (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Run tests
        run: |
          if [[ $RUNNER_OS == 'Windows' ]]; then
            gradlew.bat test
          else
            ./gradlew test
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Remote Server
        run: |
          ssh user@Someone "cd /path/to/app && git pull && ./deploy.sh"
